### ISSUE TITLE
PagedJS with mobile devices

### ISSUE THREAD

**Issue by evanfrawley** [pagedjs/pagedjs#116]
Is PagedJS generally incompatible with mobile? I am running into an issue where my page previews get cut off. I went to check against some of the PagedJS examples. Below is the Moby Dick example from the readme. Notice there are 2 very thin columns, whereas on desktop, the pages render as expected.

Would love any insight into how you all might debug this. Thanks!

![image](https://user-images.githubusercontent.com/13992385/210830884-0fd46b32-070f-480d-a7e7-723561a222d4.png)

**Comment by julientaq** [comment]
Hi there.

Pagedjs is a library to generate pdf and printed matters and is not made for reading pagination on screen. 
the vast majority of the features we polyfill aren’t event though about by the vendors on mobile.

I’m closing the issue because it’s outside the scope of what we do.
please feel free to answer if you want a follow up.
