### ISSUE TITLE
The last line of text from a print page is sometimes not fully visible

### ISSUE THREAD

**Issue by mflorea** [pagedjs/pagedjs#157]
When a text (e.g. a paragraph) doesn't fit the current print page we first try to add as many words as we can until we find the word that overflows. If the overflow is just before a word, we simply split the text before that word. Otherwise, if the overflow is **within** the word then we add as many letters as we can (from that word) until we find the letter that doesn't fit. Then we split before that letter.

The problem is that when we check if a letter from the overflowing word fits the page we actually check if the letter **starts** inside the current print page (we check for the top and left boundary of the letter). We should instead check if the letter is fully inside the boundaries of the current print page by looking at the bottom and right letter boundaries.

**Comment by tmasabari** [comment]
Thanks for reporting the issue and the solution. I also faced a similar issue within a table cell. 

I provided an improvement to the pull request to move the entire row, if the beginning of the cell itself is not accommodated within a page.

**Comment by tmasabari** [comment]
This is an improvement over the existing pull request https://github.com/pagedjs/pagedjs/pull/158

1. If the beginning of the cell itself is not accommodated within a page, the code will move the entire row, instead of moving just the remaining cells.
2. The page and container bounds are reduced/floored, the content/node bounds are ceiled to make sure there are no overflows.
3. Fixed the overflowing problem, when none of the text is overlapping but the padding, border, margin of the element is exceeding the page.
4. The original fix is to be applied while checking at the node text level as well 'check if the letter is fully inside the boundaries of the current print page by looking at the bottom and right letter boundaries.'

**Comment by tmasabari** [comment]
I tested above fix with my library and it is working fine
### Without the fix
![image](https://github.com/pagedjs/pagedjs/assets/3268355/fefd9576-7371-4f16-8cd6-d7c706a136f7)


### **After the fix**
![image](https://github.com/pagedjs/pagedjs/assets/3268355/31f38ff9-f7b7-45ba-aa3e-c9f4aefd5775)
