### ISSUE TITLE
Named Pages result in empty pages

### ISSUE THREAD

**Issue by schwiet** [pagedjs/pagedjs#20]
version 0.1.40

I'm trying to use Named pages, so I can apply different rules to groups of pages. Following the example in the documentation, I'm trying something like:

    <section class='cover'>
        <h1>Cover text</h1>
        
    </section>
    <section class='toc'>
        <h1>Table of Contents</h1>
        
    </section>
    <section class='contents'>
        <h1>Chapter 1</h1>
        
    </section>
with styles:

    @media print {

        .cover,
        .toc {
            page: frontmatter;
        }

        .content {
            page: content;
        }

        .content h1#introduction{
            counter-reset: page 1;
        }

        @page {
            size: A4;
            margin: 0.5in 0.5in 0.5in 0.5in;
        }

        @page content {
            @bottom-right{
                content: 'Page ' counter( page );
            }
        }

        @page frontmatter{
            @bottom-right{
                content: counter( page, upper-roman );
            }
        }
    }

This results in a blank page being inserted before `<section>`. Additionally, the first page of `section.content` _does_ get numbered page 1, but the following is numbered page 3.

    ----------
    |  blank |
    |        |
    |        |
    ----------
    ----------
    |  cover |
    |        |
    |    II  |
    ----------
    ----------
    |  blank |
    |        |
    |        |
    ----------
    ----------
    |  TOC   |
    |        |
    |    IV  |
    ----------
    ----------
    |  blank |
    |        |
    |    p5  |
    ----------
    ----------
    |  Ch 1  |
    |        |
    |    p1  |
    ----------
    ----------
    |  Ch 2  |
    |        |
    |    p3  |
    ----------
    ----------
    |  blank |
    |        |
    |        |
    ----------

Would really like to use PagedJS, thanks for your work on it. I hope I'm just doing something wrong 🤞

**Comment by julientaq** [comment]
Hi there!

sorry, i was away and didnt see your issue.

So it’s either a bug or something weird in your css that would include break-before.  Can you share the files you’re working with?

**Comment by schwiet** [comment]
Sorry for the delayed reply. I think it did end up being something in my CSS 😳

**Comment by ham17ahm** [comment]
Could you share what the issue was with your CSS and how the extra blank page got resolved? I'm facing the exact same issue.

**Comment by usrlocalben** [comment]
Same situation here: Named pages w/running element markup in margin containers.
If I put the running elements inside of a page, that avoids blanks but now the pages are coupled to document-level details. 😞 
I have tried many variations of e.g. display:none, position:absolute, different containers, whitespace care to ensure no text content exists, etc -- can't seem to avoid a blank page so far.

The hack I came up with is:
- use the unwanted blank first-page as a place to put all running elements,
- reset the page counter on the real page1
- remove the blank page from the beginning of the rendered pdf

This blocks the use of the _pages_ total counter since it's off by one and there is no method to reset it.
