### ISSUE TITLE
Table Of Contents: Cross Reference goes to wrong page

### ISSUE THREAD

**Issue by catchshyam** [pagedjs/pagedjs#215]
Hello,

I have been thoroughly enjoying using this beautiful library. I don't think this is Paged specific issue. However, there is not discussion forum on this repo, so using the issue to seek help.

I have managed to generate my webpage including table of contents with NextJS and Paged. I use Puppeteer to export to PDF. The table of contents lists the chapters with hyperlink. The links work correctly on HTML. When exported to PDF, the links jump ahead by couple of pages. Has anyone faced this issue? Thank you.

**Comment by julientaq** [comment]
hi there.

do you have some code to show?
This never really happened before.

**Comment by catchshyam** [comment]
@julientaq sorry for the false alarm. This turned out to be Puppeteer issue. I am leaving the link to puppeteer bug here just incase some one comes searching for the similar issue. https://github.com/puppeteer/puppeteer/issues/12601

By the way, great work. I can't tell you how much fun I had using this library over the last week.

**Comment by Yang-Yus** [comment]
I have same issue here, all links work fine on Paged Previewer(), but when exported to PDF, the links jump ahead couple of pages(with no pattern).

Pagedjs 0.4.3  with vue component.

Also the links jump to different pages when i open exported PDF with browser(link chrome)  or with local viewer(macOS Preview).

But I'm sure this issue was not happened before. All links work perfectly

**Comment by catchshyam** [comment]
@Yang-Yus See [this comment](https://github.com/puppeteer/puppeteer/issues/12601#issuecomment-2178317100). Using Puppeteer v22.6.4 resolved it for me.

**Comment by Yang-Yus** [comment]
@catchshyam  many thanks.

So you use Puppeteer to export PDF not Pagedjs right?
according to [your refs](https://github.com/puppeteer/puppeteer/issues/12601#issuecomment-2173352353) I think this is [Bug in Chromium](https://issues.chromium.org/issues/347674894), happened in Chrome version 125, 126. still not fixed yet.
gonna try to use Puppeteer.

**Comment by Yang-Yus** [comment]
Still goes to wrong page.
Use [Minimal, reproducible example](https://github.com/puppeteer/puppeteer/issues/12601#issue-2357011808)

node  v20.12.2
puppeteer v22.6.4

Here is output file: [test.pdf](https://github.com/user-attachments/files/16346913/output.pdf)

I think maybe is because When install Puppeteer, it automatically downloads a recent version of Chrome for Testing.

**Comment by catchshyam** [comment]
@Yang-Yus can you check the exact puppeteer version that is installed. Or simply ru npm install puppeteer@v22.6.4 --save-exact

**Comment by Yang-Yus** [comment]
@catchshyam Thank you!
I think Chromium was fixed this issue(at version 127). Right now pagedjs toc links also navigate to current page.
